{% set name = "clusterx" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/clusterX-{{ version }}.tar.gz
  sha256: 1631c2105d44e598c4b8cfce5e8c77b126c38adc48da5c0ba4b11d719bf20682

build:
  entry_points:
    - cell=clusterx.cli.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-learn
    - matplotlib-base
    - ase
    - plac
    - pytest
    - spglib
    - sympy
    - nglview
    - notebook
    - ipywidgets
    - pytest-html
    - tqdm

test:
  imports:
    - clusterx
  commands:
    - pip check
    - cell --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://sol.physik.hu-berlin.de/cell/
  summary: CELL (aka clusterX) is a python package for building Cluster Expansion models of simple and complex alloys and performing thermodynamical analyses of materials.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
