{% set name = "clusterx" %}
{% set version = "2.1.0rc4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clusterX-{{ version }}.tar.gz
  sha256: 6e6a5b0b5d032095932bc69db2b1eca397d720718c76a44e0112b3952963601f

build:
  entry_points:
    - cell=clusterx.cli.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - scikit-learn
    - matplotlib-base
    - ase
    - plac
    - pytest
    - spglib
    - sympy
    - nglview
    - notebook
    - ipywidgets
    - pytest-html
    - tqdm

test:
  imports:
    - clusterx
  commands:
    - pip check
    - cell --help
  requires:
    - pip

about:
  home: http://sol.physik.hu-berlin.de/cell/
  summary: CELL (aka clusterX) is a python package for building Cluster Expansion models of simple and complex alloys and performing thermodynamical analyses of materials.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
